---
title: "p8105_hw6_mz2662_pj2325" 
author: "Mengqi Zhu (mz2662) & Pengfei Jiang (pj2325)"
output: html_document
---

<br>

### **P8105 Homework 6**

<br>
The New York City Department of Health and Mental Hygiene (DOHMH) conducts unannounced restaurant inspections on an annual basis in order to check for compliance with policies on food handling, food temperature, personal hygiene of restaurant workers, and vermin control. Regulation violations are each worth a pre-specified number of points, which are totaled at the end of the inspection. Scores are converted into grades, where a lower score earns a higher grade.

Each violation falls into one of three categories:

A public health hazard, such as failing to store food at an appropriate temperature, results in a minimum score of 7

A critical violation, such as improperly washing raw vegetables prior to serving, results in a minimum score of 5

A general violation, such as improperly sanitizing cookware, results in a minimum score of 2

Additional points can then be assigned based on the severity of the violation, ranging from 1-5, at the discretion of the inspector.

Dashboard dataset relevant processing steps:

In the scatterplot, we plot the average score by boro and cuisine against the A percentage. From the plot, we can clearly see that the lower average score a boro has, the higher percentage of grade A restaurants there will be. We can find out which cuisine of which boro is the best form the plot, which is quite interesting.

In the box plot, we plot the distribution of score by cuisine. From the plot, we can see that the score of Chinese food is mostly biased and cafes tend to have the lowest overall score (which means the best). 

In the bar-plot, we plot the average score of different cuisines. We can see the average scores of cuisines form the plot, which provides us a good view of cuisines in a boro,too.



1: Here is our [**Dashboard**](nyc_restaurant_flexboard.html)

2: Here is our [**Shiny Webpage**](https://pengfeijiang.shinyapps.io/nyc_restaurant_shiny/)

3: Here is our [**Main Repository**](https://github.com/WendyThe13th/p8105_hw6)

4: Here is our [**Shiny Repository**](https://github.com/pengfeijiang/p8105_hw6_mz2662_pj2325_shiny)
 

