---
title: "P8105 Homework 6: NYC Restaurant Flexboard"
author: "Mengqi Zhu (mz2662) & Pengfei Jiang (pj2325)"
date: "November 13, 2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
rm(list = ls())
library(readxl)
library(tidyverse)
library(janitor)
library(stringr)
library(plotly)
library(flexdashboard)
```


```{r, chunk1}
#read and clean data
nyc_inspections <- 
  read_csv("../data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>%
  clean_names() %>%
  filter(grade %in% c("A", "B", "C"),
         boro != "Missing") %>% 
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro)) %>% 
  select(inspection_num, boro, grade, score, critical_flag, cuisine_description)
```

Column {data-width=500}
-----------------------------------------------------------------------

### Grade A Percentage vs Average Score ScatterPlot

```{r, chunk2, message = FALSE, warning = FALSE}
nyc_inspections %>%
  group_by(boro, cuisine_description) %>%
  summarise(aver_score = mean(score),
            num_inspections = n(),
            A_num = sum(grade == "A"),
            A_percent = sum(grade == "A")/n(),
            critaical_percent = sum(grade == "A")/n()) %>%
  mutate(text_label = str_c("Boro: ", boro, '\nCuisine: ', cuisine_description, 
                            '\nnumber of inspection:', num_inspections, '\nnumber of A:', A_num,
                            '\n A%:', paste(round(A_percent*100,digits = 2),"%",sep = "")), 
                            '\n critical%:', paste(round(critaical_percent*100,digits = 2),"%",sep = "")) %>%
  plot_ly(x = ~A_percent, y = ~aver_score, type = "scatter", mode = "markers",   
          alpha = 0.7, color = ~boro, text = ~text_label)


```

Column {data-width=450}
-----------------------------------------------------------------------

### Boxplot of Scores

```{r, chunk3}

cuisine_boxplot <-
  nyc_inspections %>%
  filter(boro == "Manhattan") %>%
  group_by(cuisine_description) %>%
  summarise(num_inspections = n()) %>%
  top_n(5, num_inspections) %>%
  pull(cuisine_description)

nyc_inspections %>%
  filter(boro == "Manhattan",
         cuisine_description %in% cuisine_boxplot) %>%
  plot_ly(y = ~score, color = ~cuisine_description, type = "box", colors = "Set2")
```

### Bar-plot for Average Scores by Cuisine

```{r, chunk4, message = FALSE, warning =FALSE}
nyc_inspections %>%
  group_by(boro, cuisine_description) %>%
  summarise(aver_score = mean(score),
            num_inspections = n(),
            A_num = sum(grade == "A"),
            A_percent = sum(grade == "A")/n(),
            critaical_percent = sum(grade == "A")/n()) %>%
  mutate(text_label = str_c("Boro: ", boro, '\nCuisine: ', cuisine_description, 
                            '\nnumber of inspection:', num_inspections, '\nnumber of A:', A_num,
                            '\n A%:', paste(round(A_percent*100, digits = 2),"%",sep = "")), 
                            '\n critical%:', paste(round(critaical_percent*100, digits = 2),"%",sep = "")) %>%
  filter(boro == "Manhattan") %>%
  plot_ly(x = ~cuisine_description, y = ~aver_score, color = ~cuisine_description, type = "bar", text = ~text_label) %>%
  layout(showlegend = FALSE)
```



